// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxyalsdbfwgroixvxyrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4eWFsc2RiZndncm9peHZ4eXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzIzMzEsImV4cCI6MjA2MDkwODMzMX0.Q1lIqPlm06Z9Ly6ZrGymcUW-DSvD-D_hozkeAmd0EPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);